### ISSUE TITLE
Did you get the encrypted matrix messages sending to work? 

### ISSUE THREAD

**Issue by select** [guardianproject/ractive#9]
I'm currently trying to get encrypted messages to work and had a look at https://github.com/guardianproject/ractive/blob/master/bot.js 
I tried to use your code but so far I was not successful sending a message, did you get it to work?

**Comment by n8fr8** [comment]
No. I ended up switching to the Pantalaimon encryption proxy that Matrix offers: https://github.com/matrix-org/pantalaimon

It actually worked perfectly, and wasn't as bad of a hack as I thought.

**Comment by select** [comment]
I banged my head long enough against it and got it working https://github.com/matrix-org/matrix-js-sdk/issues/731
Also thanks to your code ;)
